// Code generated by mediator boilerplate; DO NOT EDIT.
package main

import (
	"github.com/celskeggs/mediator/platform/atoms"
	"github.com/celskeggs/mediator/platform/datum"
	"github.com/celskeggs/mediator/platform/types"
)

type TurfImpl struct {
	atoms.TurfData
	atoms.AtomData
	ExtAtomData
	datum.DatumData
}

func NewTurf(realm *types.Realm, params ...types.Value) *types.Datum {
	i := &TurfImpl{}
	d := realm.NewDatum(i)
	datum.NewDatumData(d, &i.DatumData, params...)
	NewExtAtomData(d, &i.ExtAtomData, params...)
	atoms.NewAtomData(d, &i.AtomData, params...)
	atoms.NewTurfData(d, &i.TurfData, params...)
	return d
}

func (t *TurfImpl) Type() types.TypePath {
	return "/turf"
}

func (t *TurfImpl) Var(src *types.Datum, name string) (types.Value, bool) {
	switch name {
	case "type":
		return types.TypePath("/turf"), true
	case "parent_type":
		return types.TypePath("/atom"), true
	case "appearance":
		return t.AtomData.VarAppearance, true
	case "density":
		return types.Int(t.AtomData.VarDensity), true
	case "opacity":
		return types.Int(t.AtomData.VarOpacity), true
	case "verbs":
		return datum.NewListFromSlice(t.AtomData.VarVerbs), true
	case "contents":
		return t.AtomData.GetContents(src), true
	case "desc":
		return t.AtomData.GetDesc(src), true
	case "dir":
		return t.AtomData.GetDir(src), true
	case "icon":
		return t.AtomData.GetIcon(src), true
	case "icon_state":
		return t.AtomData.GetIconState(src), true
	case "layer":
		return t.AtomData.GetLayer(src), true
	case "loc":
		return t.AtomData.GetLoc(src), true
	case "name":
		return t.AtomData.GetName(src), true
	case "suffix":
		return t.AtomData.GetSuffix(src), true
	case "x":
		return t.TurfData.GetX(src), true
	case "y":
		return t.TurfData.GetY(src), true
	case "z":
		return t.TurfData.GetZ(src), true
	default:
		return nil, false
	}
}

func (t *TurfImpl) SetVar(src *types.Datum, name string, value types.Value) types.SetResult {
	switch name {
	case "type":
		return types.SetResultReadOnly
	case "parent_type":
		return types.SetResultReadOnly
	case "appearance":
		t.AtomData.VarAppearance = value.(atoms.Appearance)
		return types.SetResultOk
	case "density":
		t.AtomData.VarDensity = types.Unint(value)
		return types.SetResultOk
	case "opacity":
		t.AtomData.VarOpacity = types.Unint(value)
		return types.SetResultOk
	case "verbs":
		t.AtomData.VarVerbs = datum.ElementsAsType([]atoms.Verb{}, value).([]atoms.Verb)
		return types.SetResultOk
	case "contents":
		return types.SetResultReadOnly
	case "desc":
		t.AtomData.SetDesc(src, value)
		return types.SetResultOk
	case "dir":
		t.AtomData.SetDir(src, value)
		return types.SetResultOk
	case "icon":
		t.AtomData.SetIcon(src, value)
		return types.SetResultOk
	case "icon_state":
		t.AtomData.SetIconState(src, value)
		return types.SetResultOk
	case "layer":
		t.AtomData.SetLayer(src, value)
		return types.SetResultOk
	case "loc":
		t.AtomData.SetLoc(src, value)
		return types.SetResultOk
	case "name":
		t.AtomData.SetName(src, value)
		return types.SetResultOk
	case "suffix":
		t.AtomData.SetSuffix(src, value)
		return types.SetResultOk
	case "x":
		t.TurfData.SetX(src, value)
		return types.SetResultOk
	case "y":
		t.TurfData.SetY(src, value)
		return types.SetResultOk
	case "z":
		t.TurfData.SetZ(src, value)
		return types.SetResultOk
	default:
		return types.SetResultNonexistent
	}
}

func (t *TurfImpl) Proc(src *types.Datum, usr *types.Datum, name string, params ...types.Value) (types.Value, bool) {
	switch name {
	case "Bump":
		return t.AtomData.ProcBump(src, usr, types.Param(params, 0)), true
	case "Bumped":
		return t.ExtAtomData.ProcBumped(src, usr, params), true
	case "Enter":
		return t.TurfData.ProcEnter(src, usr, types.Param(params, 0), types.Param(params, 1)), true
	case "Entered":
		return t.TurfData.ProcEntered(src, usr, types.Param(params, 0), types.Param(params, 1)), true
	case "Exit":
		return t.TurfData.ProcExit(src, usr, types.Param(params, 0), types.Param(params, 1)), true
	case "Exited":
		return t.TurfData.ProcExited(src, usr, types.Param(params, 0), types.Param(params, 1)), true
	case "Move":
		return t.AtomData.ProcMove(src, usr, types.Param(params, 0), types.Param(params, 1)), true
	case "New":
		return t.DatumData.ProcNew(src, usr), true
	case "Stat":
		return t.AtomData.ProcStat(src, usr), true
	default:
		return nil, false
	}
}

func (t *TurfImpl) SuperProc(src *types.Datum, usr *types.Datum, chunk string, name string, params ...types.Value) (types.Value, bool) {
	switch chunk {
	case "github.com/celskeggs/mediator/platform/atoms.TurfData":
		switch name {
		case "Exit":
			return t.AtomData.ProcExit(src, usr, types.Param(params, 0), types.Param(params, 1)), true
		case "Enter":
			return t.AtomData.ProcEnter(src, usr, types.Param(params, 0), types.Param(params, 1)), true
		case "Exited":
			return t.AtomData.ProcExited(src, usr, types.Param(params, 0), types.Param(params, 1)), true
		case "Entered":
			return t.AtomData.ProcEntered(src, usr, types.Param(params, 0), types.Param(params, 1)), true
		}
	}
	return nil, false
}

func (t *TurfImpl) ProcSettings(name string) (types.ProcSettings, bool) {
	switch name {
	case "Bump":
		return types.ProcSettings{}, true
	case "Bumped":
		return types.ProcSettings{}, true
	case "Enter":
		return types.ProcSettings{}, true
	case "Entered":
		return types.ProcSettings{}, true
	case "Exit":
		return types.ProcSettings{}, true
	case "Exited":
		return types.ProcSettings{}, true
	case "Move":
		return types.ProcSettings{}, true
	case "New":
		return types.ProcSettings{}, true
	case "Stat":
		return types.ProcSettings{}, true
	default:
		return types.ProcSettings{}, false
	}
}

func (t *TurfImpl) Chunk(ref string) interface{} {
	switch ref {
	case "github.com/celskeggs/mediator/platform/atoms.TurfData":
		return &t.TurfData
	case "github.com/celskeggs/mediator/platform/atoms.AtomData":
		return &t.AtomData
	case "github.com/celskeggs/mediator-examples/yourfirstworld.ExtAtomData":
		return &t.ExtAtomData
	case "github.com/celskeggs/mediator/platform/datum.DatumData":
		return &t.DatumData
	default:
		return nil
	}
}
